export type Product = {
  title: string;
  description: string;
};

export const products: Product[] = [
  {
    title: "Solar Panels",
    description:
      "High-quality solar panels designed to convert sunlight into clean and reliable electricity.",
  },
  {
    title: "Solar Inverters",
    description:
      "Efficient solar inverters that convert and manage the electricity generated by your solar system.",
  },
  {
    title: "Battery Storage",
    description:
      "Energy storage solutions that allow you to store solar power for use when it is needed.",
  },
  {
    title: "Complete Solar Systems",
    description:
      "Integrated solar solutions combining the essential components needed for a complete solar energy system.",
  },
];